site:
    title: "翁の微语"
    subtitle: "一个博客 · 一方净土"
    limit: 10
    theme: theme
    lang: zh
    url: "http://blog.e123.pw/"
    comment: username
    logo: ""
    # link: "{category}/{year}/{month}/{day}/{title}.html"
    # root: "/blog"

authors:
    me:
        name: "某翁"
        intro: "一个普通学生而已x"
        avatar: "https://q.qlogo.cn/qqapp/100229475/B9BC376B79B4620E5E437DC3CD51F089/100"

build:
    # output: "public"
    port: 8000
    # Copied files to public folder when build
    copy:
        - "source/images"
    # Excuted command when use 'ink publish'
    publish: |
        cd blog
        git add . -A
        git commit -m "update blog"
        git push --set-upstream origin master
